services:
  database:
    image: postgis/postgis:16-3.4-alpine
    pull_policy: if_not_present
    container_name: postgis
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - database
    ports:
      - 5434:5432
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    pull_policy: if_not_present
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - database
    restart: unless-stopped

  geoserver:
    image: docker.osgeo.org/geoserver:2.25.2
    container_name: geoserver
    volumes:
      - geoserver:/opt/geoserver/data_dir
    ports:
      - "8080:8080"
    networks:
      - database

networks:
  database:
    driver: bridge
  geoserver:
    driver: bridge

volumes:
  database:
  pgadmin:
  geoserver: