logging:
  level: ERROR
metadata:
  contact:
    address: Mailing Address
    city: City
    country: Country
    email: you@example.org
    fax: +xx-xxx-xxx-xxxx
    hours: Mo-Fr 08:00-17:00
    instructions: During hours of service. Off on weekends.
    name: Lastname, Firstname
    phone: +xx-xxx-xxx-xxxx
    position: Position Title
    postalcode: Zip or Postal Code
    role: pointOfContact
    stateorprovince: Administrative Area
    url: Contact URL
  identification:
    description:
      en: pygeoapi provides an API to geospatial data
      fr: "pygeoapi fournit une API aux donn\xE9es g\xE9ospatiales"
    keywords:
      en:
      - geospatial
      - data
      - api
      fr:
      - "g\xE9ospatiale"
      - "donn\xE9es"
      - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    title:
      en: pygeoapi default instance
      fr: "instance par d\xE9faut de pygeoapi"
    url: https://example.org
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Organization Name
    url: https://pygeoapi.io
resources:
  lakes:
    description:
      en: lakes of the world, public domain
      fr: lacs du monde, domaine public
    extents:
      spatial:
        bbox:
        - -180
        - -90
        - 180
        - 90
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 2011-11-11 11:11:11+00:00
        end: null
    keywords:
      en:
      - lakes
      - water bodies
      fr:
      - lacs
      - plans d'eau
    links:
    - href: http://www.naturalearthdata.com/
      hreflang: en-US
      rel: canonical
      title: information
      type: text/html
    providers:
    - data: ne_110m_lakes.geojson
      id_field: id
      name: GeoJSON
      title_field: name
      type: feature
    title:
      en: Large Lakes
      fr: Grands Lacs
    type: collection
  mapserver_world_map:
    description: MapServer demo WMS world map
    extents:
      spatial:
        bbox:
        - -180
        - -90
        - 180
        - 90
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    keywords:
    - MapServer
    - world map
    links:
    - href: https://demo.mapserver.org
      hreflang: en-US
      rel: canonical
      title: information
      type: text/html
    providers:
    - data: https://demo.mapserver.org/cgi-bin/msautotest
      format:
        mimetype: image/png
        name: png
      name: WMSFacade
      options:
        layer: world_latlong
        style: default
      type: map
    title: MapServer demo WMS world map
    type: collection
server:
  bind:
    host: 0.0.0.0
    port: 5001
  encoding: utf-8
  gzip: false
  languages:
  - en-US
  - fr-CA
  limit: 10
  map:
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap
      contributors</a>'
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  mimetype: application/json; charset=UTF-8
  pretty_print: true
  url: http://localhost:5001
